let suggestions = [
    
    "BRITANNIA.NS",
    "INDUSINDBK.NS",
    "COALINDIA.NS",
    "WIPRO.NS",
    "BHARTIARTL.NS",
    "ICICIBANK.NS",
    "TATASTEEL.NS",
    "RELIANCE.NS",
    "TECHM.NS",
    "BAJAJ-AUTO.NS",
    "HDFCLIFE.NS",
    "TATACONSUM.NS",
    "BAJFINANCE.NS",
    "LT.NS",
    "HINDALCO.NS",
    "TCS.NS",
    "NESTLEIND.NS",
    "NTPC.NS",
    "ULTRACEMCO.NS",
    "SHREECEM.NS",
    "CIPLA.NS",
    "TITAN.NS",
    "HEROMOTOCO.NS",
    "KOTAKBANK.NS",
    "BAJAJFINSV.NS",
    "ITC.NS",
    "MARUTI.NS",
    "APOLLOHOSP.NS",
    "MM.NS",
    "ONGC.NS",
    "SBIN.NS",
    
];